name: Sync Issues to JIRA

on:
  issues:
    types: [opened, reopened, closed]

jobs:
  update:
    name: Update Issue
    uses: canonical/sdcore-github-workflows/.github/workflows/issues.yaml@v2.0.0
    secrets: inherit
